services:
  api:
    build: .
    ports:
      - 8000:8000
    image: minecraft-api
    volumes:
      - ~/.aws:/root/.aws
      - .:/app
    environment:
      - AWS_PROFILE=mlops-club
      - DEV_PORT=8000
      - MINECRAFT_SERVER_STATE_MACHINE_ARN=arn:aws:states:us-west-2:630013828440:stateMachine:awscdkminecraftProvisionMcStateMachineawscdkminecraftProvisionMcSta-aDmssJYgrn9o
      - ENVIRONMENT=development
