/* tslint:disable */
/* eslint-disable */
/**
 * 🎁 Minecraft Platform-as-a-Service API 🎄
 * A FastAPI app for the Minecraft API.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
